allowBuilds:
  '@biomejs/biome': true
  '@swc/core': true
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  lefthook: true
nodeLinker: hoisted
shamefullyHoist: true
